<?php

namespace Mublo\Core\Install;

use PDO;
use PDOException;
use Exception;
use Mublo\Infrastructure\Crypto\CryptoManager;

/**
 * DatabaseConfigWriter
 *
 * DB 연결 테스트 및 config/database.php 파일 생성
 */
class DatabaseConfigWriter
{
    private CryptoManager $crypto;

    public function __construct()
    {
        $this->crypto = new CryptoManager();
    }
    /**
     * DB 연결 테스트
     */
    public function testConnection(array $config): array
    {
        try {
            $dsn = sprintf(
                'mysql:host=%s;port=%s;charset=%s',
                $config['host'],
                $config['port'],
                $config['charset']
            );

            $pdo = new PDO(
                $dsn,
                $config['username'],
                $config['password'],
                [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                ]
            );

            // 데이터베이스 존재 확인
            $stmt = $pdo->prepare("SHOW DATABASES LIKE ?");
            $stmt->execute([$config['database']]);
            $dbExists = $stmt->rowCount() > 0;
            $stmt->closeCursor();

            if (!$dbExists) {
                // 데이터베이스가 없으면 자동 생성
                try {
                    $pdo->exec("CREATE DATABASE `{$config['database']}`
                               CHARACTER SET {$config['charset']}
                               COLLATE {$config['collation']}");
                    $dbCreated = true;
                } catch (PDOException $createException) {
                    return [
                        'success' => false,
                        'message' => "데이터베이스 생성 실패: {$createException->getMessage()}. CREATE DATABASE 권한이 있는지 확인하세요.",
                    ];
                }
            } else {
                $dbCreated = false;
            }

            // 데이터베이스 선택
            $pdo->exec("USE `{$config['database']}`");

            $message = $dbCreated
                ? "DB 연결 성공 (데이터베이스 '{$config['database']}' 생성됨)"
                : 'DB 연결 성공';

            return [
                'success' => true,
                'message' => $message,
                'server_version' => $pdo->getAttribute(PDO::ATTR_SERVER_VERSION),
                'db_created' => $dbCreated,
            ];
        } catch (PDOException $e) {
            return [
                'success' => false,
                'message' => 'DB 연결 실패: ' . $e->getMessage(),
            ];
        }
    }

    /**
     * config/database.php 파일 생성
     */
    public function writeConfig(array $config): bool
    {
        $configPath = MUBLO_CONFIG_PATH . '/database.php';

        // 암호화 키 생성 (비밀번호 암호화용)
        $encryptKey = $this->crypto->generateShortKey();

        // 비밀번호 암호화
        $encryptedPassword = $this->crypto->encrypt($config['password'], $encryptKey);

        $content = <<<PHP
<?php
/**
 * Database Configuration
 * Auto-generated by Mublo Framework Installer
 * Created at: {$this->getCurrentDateTime()}
 */

return [
    'connection' => 'mysql',

    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'host' => '{$config['host']}',
            'port' => {$config['port']},
            'database' => '{$config['database']}',
            'username' => '{$config['username']}',
            'password' => '{$encryptedPassword}',
            'charset' => '{$config['charset']}',
            'collation' => '{$config['collation']}',
            '_encrypted' => true,
            '_encrypt_key' => '{$encryptKey}',
        ],
    ],

    'options' => [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ],
];

PHP;

        $result = file_put_contents($configPath, $content);

        if ($result === false) {
            return false;
        }

        // 파일 권한 설정 (읽기 전용)
        @chmod($configPath, 0644);

        return true;
    }

    /**
     * 현재 시간 반환
     */
    private function getCurrentDateTime(): string
    {
        return date('Y-m-d H:i:s');
    }

    /**
     * mysqli 연결 생성 (마이그레이션 전용)
     *
     * PDO는 DDL 다량 실행 시 unbuffered query 에러가 발생하므로
     * 마이그레이션/시더에는 mysqli를 사용.
     */
    private function createMysqli(array $config): \mysqli
    {
        $mysqli = new \mysqli(
            $config['host'],
            $config['username'],
            $config['password'],
            $config['database'],
            (int) $config['port']
        );

        if ($mysqli->connect_error) {
            throw new \RuntimeException('DB 연결 실패: ' . $mysqli->connect_error);
        }

        $mysqli->set_charset($config['charset'] ?? 'utf8mb4');

        return $mysqli;
    }

    /**
     * SQL 파일의 개별 문장을 순차 실행
     *
     * 세미콜론으로 분리 후 각각 query()로 실행.
     * 멱등성 에러(중복 컬럼/키 등)는 건너뛰고 계속 진행.
     */
    private function executeSqlViaMysqli(\mysqli $mysqli, string $sql): void
    {
        $queries = array_filter(
            array_map('trim', explode(';', $sql)),
            fn($q) => !empty($q)
        );

        foreach ($queries as $query) {
            try {
                $mysqli->query($query);
            } catch (\mysqli_sql_exception $e) {
                if ($this->isMysqliIdempotentError($e->getCode())) {
                    continue;
                }
                throw $e;
            }
        }
    }

    /**
     * DB 마이그레이션 실행
     */
    public function runMigrations(array $config): array
    {
        try {
            $mysqli = $this->createMysqli($config);

            // 마이그레이션 파일 경로
            $migrationPath = MUBLO_ROOT_PATH . '/database/migrations';

            if (!is_dir($migrationPath)) {
                $mysqli->close();
                return [
                    'success' => false,
                    'message' => '마이그레이션 디렉토리가 존재하지 않습니다.',
                ];
            }

            // 마이그레이션 파일 로드
            $files = glob($migrationPath . '/*.sql');
            sort($files);

            $executed = [];

            // 기존 테이블 삭제 (재설치 지원)
            $this->dropExistingTablesMysqli($mysqli);

            // 마이그레이션 추적 테이블 선행 생성
            $mysqli->query("CREATE TABLE IF NOT EXISTS `schema_migrations` (
                `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                `source`      ENUM('core', 'plugin', 'package') NOT NULL DEFAULT 'plugin',
                `name`        VARCHAR(100) NOT NULL,
                `file`        VARCHAR(200) NOT NULL,
                `executed_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                UNIQUE KEY `uk_migration` (`name`, `file`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

            // Core 마이그레이션 실행
            foreach ($files as $file) {
                $sql = file_get_contents($file);
                $sql = $this->stripSqlComments($sql);
                if (!empty(trim($sql))) {
                    $this->executeSqlViaMysqli($mysqli, $sql);
                }
                $executed[] = basename($file);
            }

            // 마이그레이션 이력 기록
            $this->recordCoreMigrationsMysqli($mysqli, $executed);

            // default:true 패키지 마이그레이션 실행
            $defaultPackages = $this->getDefaultPackages();
            foreach ($defaultPackages as $packageName) {
                $pkgPath = MUBLO_PACKAGE_PATH . '/' . $packageName . '/database/migrations';
                if (!is_dir($pkgPath)) {
                    continue;
                }

                $pkgFiles = glob($pkgPath . '/*.sql') ?: [];
                sort($pkgFiles);

                foreach ($pkgFiles as $file) {
                    $sql = file_get_contents($file);
                    $sql = $this->stripSqlComments($sql);
                    if (!empty(trim($sql))) {
                        $this->executeSqlViaMysqli($mysqli, $sql);
                    }
                    $executed[] = $packageName . '/' . basename($file);
                }

                $this->recordPackageMigrationsMysqli($mysqli, $packageName, $pkgFiles);
            }

            $mysqli->close();

            return [
                'success' => true,
                'message' => count($executed) . '개 마이그레이션 파일 실행 완료',
                'files' => $executed,
            ];
        } catch (\Exception $e) {
            return [
                'success' => false,
                'message' => '마이그레이션 실행 실패: ' . $e->getMessage(),
            ];
        }
    }

    /**
     * SQL 파일에서 -- 주석 라인 제거
     */
    private function stripSqlComments(string $sql): string
    {
        $lines = explode("\n", $sql);
        $lines = array_filter($lines, fn($line) => !str_starts_with(trim($line), '--'));
        return implode("\n", $lines);
    }

    /**
     * 실행된 Core 마이그레이션을 schema_migrations 테이블에 기록
     */
    private function recordCoreMigrationsMysqli(\mysqli $mysqli, array $filenames): void
    {
        $stmt = $mysqli->prepare(
            "INSERT IGNORE INTO `schema_migrations` (source, name, file) VALUES ('core', '__core__', ?)"
        );
        if (!$stmt) {
            return;
        }
        foreach ($filenames as $filename) {
            $stmt->bind_param('s', $filename);
            $stmt->execute();
        }
        $stmt->close();
    }

    /**
     * manifest.json에서 default:true인 패키지 목록 반환
     */
    private function getDefaultPackages(): array
    {
        $packagePath = MUBLO_PACKAGE_PATH;
        if (!is_dir($packagePath)) {
            return [];
        }

        $defaults = [];
        foreach (glob($packagePath . '/*/manifest.json') as $manifestFile) {
            $manifest = json_decode(file_get_contents($manifestFile), true);
            if (!empty($manifest['default']) && !empty($manifest['name'])) {
                $defaults[] = $manifest['name'];
            }
        }

        return $defaults;
    }

    /**
     * 패키지 마이그레이션 이력 기록
     */
    private function recordPackageMigrationsMysqli(\mysqli $mysqli, string $packageName, array $files): void
    {
        $stmt = $mysqli->prepare(
            "INSERT IGNORE INTO `schema_migrations` (source, name, file) VALUES ('package', ?, ?)"
        );
        if (!$stmt) {
            return;
        }
        foreach ($files as $file) {
            $basename = basename($file);
            $stmt->bind_param('ss', $packageName, $basename);
            $stmt->execute();
        }
        $stmt->close();
    }

    /**
     * ALTER TABLE 멱등성 관련 무시 가능 에러인지 확인 (mysqli 에러코드)
     */
    private function isMysqliIdempotentError(int $errno): bool
    {
        return in_array($errno, [
            1060, // Duplicate column name
            1054, // Unknown column (DROP 대상 없음)
            1061, // Duplicate key name
            1072, // Key column doesn't exist
            1091, // Can't DROP; check column/key exists
            1050, // Table already exists
        ], true);
    }

    private function dropExistingTablesMysqli(\mysqli $mysqli): void
    {
        $mysqli->query('SET FOREIGN_KEY_CHECKS = 0');

        $result = $mysqli->query('SHOW TABLES');
        $tables = [];
        if ($result) {
            while ($row = $result->fetch_row()) {
                $tables[] = $row[0];
            }
            $result->free();
        }

        foreach ($tables as $table) {
            $mysqli->query("DROP TABLE IF EXISTS `{$table}`");
        }

        $mysqli->query('SET FOREIGN_KEY_CHECKS = 1');
    }
}
